# Generated by Django 3.2.12 on 2022-11-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('Region', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=10)),
                ('Product', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField(max_length=10)),
                ('UnitPrice', models.FloatField(max_length=10)),
            ],
        ),
    ]
